version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  client:
    build: ./client
    ports:
      - "5000:5000"
  server: # name of the first service
    build: ./server # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
